### ISSUE TITLE
CodeSandbox examples with descriptions.

### ISSUE THREAD

**Issue by JustFly1984** [JustFly1984/react-google-maps-api#110]
A lot of people like to share code at codesandbox.io. 

It could be nice to have some place to keep easy updated list of examples. I propose to keep this issue pinned on top, so everybody could share their examples, and we will update top comment time to time.

That is a first one, provided by @uriklar. Can you please add description?

- https://codesandbox.io/s/x200klrl5w

**Comment by JustFly1984** [comment]
https://codesandbox.io/s/usegooglemap-repro-2z4iw hacky example of using useMap hook

**Comment by mathieu-anderson** [comment]
From [the conversation that happened on Spectrum](https://spectrum.chat/react-google-maps/general/edit-partial-answer-in-comment-what-is-the-right-approach-to-get-the-new-polygon-path-when-editing-a-polygon~06f0812d-fe63-4ca8-a7f9-721e3fbb0964), I made this small example on how to get the new values of an edited Polygon. Not sure if acceptable, but I was stuck a long time trying to tackle this!

https://codesandbox.io/s/reactgooglemapsapi-editing-a-polygon-popr2

**Comment by Angelk90** [comment]
@mathieu-anderson : 
I'm using your code, can I ask you for help on something?

**Comment by mathieu-anderson** [comment]
@Angelk90 Absolutely! What is your issue?

**Comment by Angelk90** [comment]
@mathieu-anderson , @JustFly1984 : 

I'll explain what to do.

Example link: https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-jd7g1

I have an empty map, on this map I have to draw an area, a polygon.
When the polygon is finished.
User can decide whether:
- Modify the points already inserted, therefore by moving the point or the marker that identifies the point, the original point of the polygon is modified.
- Delete a point, right button at the moment.
- Add more points.
- Search using StandaloneSearchBox, the area where to draw the polygon.

The problems are as follows:
- Sometimes it gives me the problem "You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors."
I don't understand the reason, maybe I solved it, but I don't understand how.
Could it be that the module Map component I created updated a few times, then could it give the following problem?
- I tried to insert the StandaloneSearchBox, but every time I try, it gives me errors.
- I would like to right-click on the marker instead of eliminardo to display a menu like that, where it will be possible to decide whether to delete the point or modify it using a modal.
![](https://ogigia.altervista.org/Portale/images/Articoli/Internet/Google_Maps_url_breve/3.jpg)
- Another thing I was working on but was not succeeding was the possibility if user clicked on the map after creating the polygon, insert a new point.
This point in theory had to be inserted between the two points whose distance between them was the least compared to all.
I used such a thing:
https://stackoverflow.com/a/1502821/8024296
- There is a way to be able to insert such a thing on the map but fixed, I have put putting a div with z-index, but nothing
![](https://user-images.githubusercontent.com/20476002/72150495-ebfbf580-33a5-11ea-90cf-c13ada08e1ee.png)


Can you give me some advice?
