### ISSUE TITLE
How to Test Components

### ISSUE THREAD

**Issue by rrfaria** [JustFly1984/react-google-maps-api#113]
I'm using old version 9.4.5 and looking for this one to upgrade 

but before upgrade to this, I'm looking for well tested apis 
and no one describe how to test components using this

I've created this component but I don't know row to test it with jest 

Could you create a session on documentation about how to test components ?

```js
/* global google */
import React from "react";
import PropTypes from "prop-types";
import { SearchBox } from "react-google-maps/lib/components/places/SearchBox";
import "./index.css";

const Search = ({ onSearchBoxMounted, bounds, onPlacesChanged }) => (
  <SearchBox
    ref={onSearchBoxMounted}
    bounds={bounds}
    controlPosition={google.maps.ControlPosition.TOP_CENTER}
    onPlacesChanged={onPlacesChanged}
  >
    <input
      type="text"
      placeholder="where do you want to go?"
      className="search__box"
    />
  </SearchBox>
);

Search.propTypes = {
  onSearchBoxMounted: PropTypes.func.isRequired,
  bounds: PropTypes.object,
  onPlacesChanged: PropTypes.func.isRequired
};

export default Search;
```

**Comment by JustFly1984** [comment]
Basically, you can test @react-google-maps components only with end-to-end with headless browsers, kind of tests, due to requirement to load the script. You can't write jest unit tests, nor snapshots, cos most of components does not return JSX, and those which return JSX will not work without `google-maps-api` script, loaded by <LoadScript /> component with correct API key.
