### ISSUE TITLE
Can onCenterChanged pass new center to callback? 

### ISSUE THREAD

**Issue by shawnmitchell** [JustFly1984/react-google-maps-api#114]
# onCenterChanged behavior seems odd (to me)
GoogleMap defines `onCenterChanged` prop which takes a callback in the form of `() => void`
It seems like maybe this callback should be of the form `({lat, lng}) => void` or am I thinking about this the wrong way?

**Comment by uriklar** [comment]
Hi @shawnmitchell, 
You can use our Spectrum channel next time for these type of questions (https://spectrum.chat/react-google-maps)

I agree giving the new center would have been nice of them :-) But since this is an event on the map component you can get the center by using ```map.getCenter()``` (The map instance can be retrieved by either the ```onLoad``` method or the ```useGoogleMap``` hook)

**Comment by shawnmitchell** [comment]
Thanks!

**Comment by Angelk90** [comment]
@uriklar : Can I ask you something?

**Comment by muhaimincs** [comment]
> https://spectrum.chat/react-google-maps

Spectrum not really working and helpful
