### ISSUE TITLE
Error googleMapsApiKey with process.env

### ISSUE THREAD

**Issue by maxleon52** [JustFly1984/react-google-maps-api#1550]
# Issue template

If you want to ask question, ask it in [Spectrum.chat](https://spectrum.chat/react-google-maps) or [Slack channel](https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ)

Please do not post unformatted code into issues, and please do not ask questions. Only real issues, PR or feature requests allowed. Minimal reproduction in codesandbox.io is must have.

## Your Environment

os: windows

node --version: 12+

react version? 16.8

webpack version: last

@babel version: last

@react-google-maps/api version: ^1.13.0

## basic implementation of incorrect behavior in codesandbox.com

Hello, could you explain this error to me?
![web error](https://user-images.githubusercontent.com/42389997/96346730-b9d59d80-1073-11eb-9ef9-17150a24f38f.png)

I'm using typescript:

my code:

`const Maps: React.FC = () => {
  return (
    <Container>
      <LoadScript googleMapsApiKey={process.env.REACT_APP_GOOGLE_API_KEY}>
        <GoogleMap mapContainerStyle={containerStyle} center={center} zoom={10}>
          {/* Child components, such as markers, info windows, etc. */}
          <></>
        </GoogleMap>
      </LoadScript>
    </Container>
  );
};

export default React.memo(Maps);`

**Comment by JustFly1984** [comment]
@maxleon52 it is not an error with @react-google-maps, nor typescript. Actually this is correct TypeScript behavior. If your environment does not have access to the env variable, it will be undefined.

I would recommend to use `dot-env` and `dot-env-safe` to stop the build in case of variables missing, hence undefined.

The best approach to solve your issue is saving env to const like this:

```ts
const REACT_APP_GOOGLE_KEY = process.env.REACT_APP_GOOGLE_KEY as string
```

and use const in prop.
