### ISSUE TITLE
More then one LoadScriptNext on a page doesn't work

### ISSUE THREAD

**Issue by eszthoff** [JustFly1984/react-google-maps-api#202]
# Please provide an explanation
If you add 2 components on a page, each wrapped in LoadScriptNext it breaks the page. 

I'm developing a UI library and would like add Map and Autocomplete to it. Each one has its own wrapper with loading the relevant libraries only. But when I add them both to the same page it breaks. 

The same happen if I add more then one Autocomplete to one page, which is a possibility for any website. 

## Your Environment
https://codesandbox.io/embed/xenodochial-poincare-2gfjp

## How does it behave?

It should load only one copy of all the libraries requested in the different loaders

## How should it behave correctly?

* It throws error in console
* autocomplete displayed in loading state
* map does not render

Upon rerendering the component (e.g. change code in sandbox) it works fine

It should work also when the same component with the same libraries are present multiple times on the page (e.g. more Autocomplete components on different parts of a website)

**Comment by JustFly1984** [comment]
@eszthoff The **google maps api** does not support multiple scripts on the same page, due to singleton nature. there is single `window.google` object which is overwritten by any consequent script loaded, which leads to bugs and memory leaks. Hence, there could be only one `<LoadScriptNext />` per page. 

  We wish ourselves that it could be easier, and I have an idea to reverse engineer **google maps api** and make our own async and code splitted loading, but there is so many languages and libraries variations, so task is overwhelming for library without a sponsor.

**Comment by eszthoff** [comment]
@JustFly1984 thanks for the quick reply. I understand that `window.google` should be a singleton, but in the example I gave, one `LoadScriptNext` instance loads the `maps` API while the other the `places` one. It does work if these components are loaded on the page at different time (e.g. with some navigation between them). I thought that what the `injectscript` util does when checking if the existing url is the same as of the new request. 

I wonder if it would be possible to set some global variable (or something neater) to make sure the inject script runs only once, but does run for each library.

Or do you have a better suggestion on how to handle cases where components that need the google api are not next to each other on the page. Of course we would want to delay the loading only for those components and not everything in between them.

**Comment by JustFly1984** [comment]
>> I understand that window.google should be a singleton

It is singleton. We can't do nothing about it.
