### ISSUE TITLE
refactor and adopt google-maps-infobox into main package and create <InfoBox /> component

### ISSUE THREAD

**Issue by JustFly1984** [JustFly1984/react-google-maps-api#30]
https://github.com/lucasfs7/google-maps-infobox-module

**Comment by JustFly1984** [comment]
https://github.com/tomchentw/react-google-maps/blob/master/src/components/addons/InfoBox.jsx

**Comment by uriklar** [comment]
With OverlayView, why does anyone really need an InfoBox?

**Comment by JustFly1984** [comment]
@uriklar I have no idea, I think we can safely remove it.
What do you think about removing all dependencies?

**Comment by jamesmosier** [comment]
I believe that InfoBox provides an easy way to have a popover style element that can have propagation stopped on it. This is useful for popovers that allow for user interaction. 

I also personally think the options are much simpler for this use case versus trying to do all the same things with an OverlayView. For example here are some options i am using with react-google-maps and the popover:

```
{
  closeBoxURL: '',
  pane: 'floatPane',
  enableEventPropagation: true,
  alignBottom: true,
  maxWidth: 280,
  pixelOffset: new window.google.maps.Size(-140, 0),
  infoBoxClearance: new window.google.maps.Size(20, 20),
}
```

Again, much of this might be because I'm not as experienced setting up an OverlayView for this same use case (I've only used them for custom markers), but just my 2 cents.

**Comment by JustFly1984** [comment]
So what is the status on this issue? can we close it, or leave it be?

**Comment by JustFly1984** [comment]
update?

**Comment by jamesmosier** [comment]
I’m not currently working on it, so feel free to close it if you’d like.
