### ISSUE TITLE
Doc is not complete:  WTF is existing DrawingManagerF and DrawingManager? 

### ISSUE THREAD

**Issue by mohammadsadeghforoughi** [JustFly1984/react-google-maps-api#3276]
Hey guys

I spent nearly 5 hours debugging my code, I searched the internet for the DrawingManager did not have any effect.
I read the Doc, NPM page, and many blog posts and wondered why my code is not working as expected, and accidentally I saw there is a DrawingManagerF for Functional components.
Please Add it to your document or change the behavior by adding a DrawingManagerC for Class components. 
It's 2023 and everybody is using the function component as default.

Thank you.

**Comment by JustFly1984** [comment]
@mohammadsadeghforoughi  did you look at CHANGELOG.md?

If you want docs - fix them yourself. I had been created this library 5+ years ago for my own needs and shared it with everybody. I build the docs initially, but docs lib was unmaintained for a while, and did not compile due to dependency issues with typescript and new react versions.

I'm personally haven't used it for my personal projects for 4+ years, and I maintain it at my good will. Only one person donating 10$ regularly.

If you need something - DO IT YOURSELF.

If you are not capable, how come you are expecting others to be capable and spend  their free time to solve your issues?

This is a commonly used library, and everybody facing similar issues.

There is an issue already, you haven't even looked at
