### ISSUE TITLE
@types/markerclustererplus/index.d.ts is not a module.

### ISSUE THREAD

**Issue by guins** [JustFly1984/react-google-maps-api#64]
I wanted to try out the new release @1.2.0-alpha.0, but I'm getting an error during compilation : `@types/markerclustererplus/index.d.ts is not a module.` in `lib/components/drawing/Marker.d.ts`
How can I fix that ?

**Comment by guins** [comment]
By looking at the master branch commits, I just realized you apparently patch a few things regarding the markerclusterer, but you didn't publish a new version for npm. I would be happy to try out this new release !

**Comment by uriklar** [comment]
Hi @guins . 
I don't have publishing rights to npm so you'll either have to wait until @JustFly1984 wakes up or grab the current master branch which should work

**Comment by guins** [comment]
Thanks @uriklar !
Since @JustFly1984 didn't published it yet, what's the correct way to use the master branch to test it out ? I tried to install the package directly from github `npm install --save https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api` but it doesn't work. I'm getting the following error: `npm can't find a package.json file in your current directory.` Even though the package.json seems to be there according to the Github file system.
Thanks again

**Comment by JustFly1984** [comment]
@uriklar @guins I'm not really sure why it fails, it does work for docs, but it fails on gatsby-example deploy. I'm currently reqriting google's markerclustererplus to typescript and will include it as part of the lib. I'm thinking to make it as separate module, cos it has Apache.2.0 license. Our ouwn lib is living with MIT license, so that is a problem. We can't include code with Apache 2.0 into MIT if I understand copyright correct

**Comment by JustFly1984** [comment]
@guins please try alpha 4, soon will be alpha 5
