### ISSUE TITLE
Multiple LoadScripts on same page, getting error "You have included the Google Maps JavaScript API multiple times on this page."

### ISSUE THREAD

**Issue by dlynnsmith** [JustFly1984/react-google-maps-api#705]
I have a page with conditional rendering, sometimes my component "MapWithMarkers" and sometimes "MapWith**out**Markers".  Both are defined with the layout from the docs, of GoogleMap within LoadScript.  I get the error even though the conditioning prevents them from both rendering at the same time.

How can I prevent it from loading the script if it's already there?

**Comment by JustFly1984** [comment]
@dlynnsmith Please never use multiple LoadScript components per page. You can use as many GoogleMap components inside single LoadScript as you need. LoadScript has singleton pattern, due to logic of google-maps-api itself.

**Comment by tusharshuklaa** [comment]
I need to add multiple maps on a page conditionally so I have made a small wrapper around the GoogleMap component and include that wrapper component conditionally on the page.

The wrapper already includes LoadScript component and due to this I am getting this issue of  "You have included the Google Maps JavaScript API multiple times on this page."

Any guidance on how to handle this use-case in a better way so as to avoid issues?

**Comment by JustFly1984** [comment]
Just extract LoadScript higher in Dom tree so all your maps will be children or below the LoadScript

**Comment by mschipperheyn** [comment]
I have this error on a single instance with rerenders. Your suggestion would force the script to load even if you don't need it. This script should load indemnipotently (multiple calls only lead to a single load). The way to achieve it would be to specify an id to the dom element and verify its existence before executing a script insertion.
