### ISSUE TITLE
Slow performance with a lots of markers.

### ISSUE THREAD

**Issue by jesus-hernandezmoreno** [JustFly1984/react-google-maps-api#846]
Hi, I recently updated from react-google-maps, when I have more than 30 markers the map is really slow, I noticed that when you drag on en the map, onDragEnd all markers re-render.

Tried using React.memo, but is the same.

Here's my implementation:

Map.js

```
   <Map
      center={props.mapCenter}
      onCenterChanged={props.onCenterChanged}
      onLoad={map => props.setMapRef(map)}
      mapContainerStyle={{ width: '100%', height: '100%' }}
      zoom={props.mapZoom}
      onZoomChanged={props.onZoomChanged}
    >
      {props.allMarkers.map(marker => (
        <CustomMarker
          key={marker.id}
          data={marker.data}
        />
      ))}
  </Map>
```

CustomMarker.js

```
<OverlayView
  position={{
    lat: parseFloat(latitude),
    lng: parseFloat(longitude)
  }}
  mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
  getPixelPositionOffset={getPixelPositionOffset}
>
  <MarkerContainer>
    <Marker
      icon={regularIcon}
      position={{
        lat: parseFloat(latitude),
        lng: parseFloat(longitude)
      }}
      onMouseOver={() => setOpen(true)}
      onMouseOut={() => setOpen(false)}
      onDblClick={() => showTaskModal('SHOW_MODAL', data)}
      onClick={event => clickHandler(event, data)}
      onRightClick={event => rightClickHandler(event)}
    >
      {open && (
        <InfoWindow
          position={{
            lat: parseFloat(latitude),
            lng: parseFloat(longitude)
          }}
          options={{ pixelOffset: new window.google.maps.Size(-0, -30) }}
        >
          <InfoWindowCustom data={data} />
        </InfoWindow>
      )}
    </Marker>
    {index ? <Badge>{index}</Badge> : null}
  </MarkerContainer>
</OverlayView>;
```

I'm using OverlayView and InfoWindow to display some extra data on the marker, may that also impacts performance, but React.memo didn't work.

The markers are rendered dinamically from some API, and this is how it looks:

![Map](https://user-images.githubusercontent.com/17417706/79298959-45455a80-7ea8-11ea-99f5-9c01cf5d8d83.PNG)

The first RENDERING message is when the map mounts, the other RENDERING messages appear onDragEnd.

**Comment by JustFly1984** [comment]
Please use eslint-plugin-perf-react to resolve rendering bottlenecks

**Comment by dsauerbrun** [comment]
@jesus-hernandezmoreno did you find a way to resolve this issue? I'm experiencing the same thing as well. I am using the eslint-plugin-perf-react and dont see any suggestions that are solving my problem...

I can have ~200 markers on the map at once if it's zoomed out completely which is why i limit the markers by a bounding box.

here is my implementation:

`function SimpleMap(props: any) {
    let {unpaginatedLocations} = useContext<LocationsFetch>(LocationsContext);

    return (
        <LoadScript googleMapsApiKey="<mykey>">
            <GoogleMap
                mapContainerStyle={{width: '345px', height: '210px'}}
                center={{lat: -3.745, lng: -38.523}}
                zoom={1}
                >
                    <AllMarkers unpaginatedLocations={unpaginatedLocations}></AllMarkers>
                </GoogleMap>
        </LoadScript>
    );
}

function AllMarkers(props: any) {
    const refilterLocations = () => {
        let bounds = map?.getBounds();
        filteredLocations = unpaginatedLocations.filter((x: { latitude: number; longitude: number; }) => x.latitude > bounds.getSouthWest().lat() && x.latitude < bounds.getNorthEast().lat() && x.longitude > bounds.getSouthWest().lng() && x.longitude < bounds.getNorthEast().lng());
    }

    let unpaginatedLocations = props.unpaginatedLocations;
    let filteredLocations: any[] = unpaginatedLocations;
    let map: google.maps.Map<Element> = useGoogleMap();
    refilterLocations();
    map.addListener('dragend', () => refilterLocations());


    return (
        <>
            {filteredLocations?.map(x => (<Marker key={x.latitude} position={{lat: x.latitude, lng: x.longitude}}/>))}
        </>
    );
}`

**Comment by xalisys** [comment]
@jesus-hernandezmoreno  @dsauerbrun 

I am using this library to render 2000 pins on map, it works pretty smoothly. By looking at the both of the code snippets, it seems like the issues with react practices rather than map or this library. Here are suggestions:

1. Don't use inline functions like 'onMouseOver={() => setOpen(true)}' anywher in your components, use useCallback(), inline handler to change prop in every render cycle.

2. Don't use inline objects such as  '{{lat: -3.745, lng: -38.523}}' anywhere in your components, either use constants if its static or useMemo() from react.

4. @jesus-hernandezmoreno you can pull <InfoWindow> out of Marker children to make one InfoWindow serving all markers.
 
Hope this helps!

**Comment by roshin8** [comment]
@xalisys Can you please provide an example of how you would do the Third point of pulling out InfoWindow out of Marker children adn to make one InfoWindow serve all markers?

**Comment by JustFly1984** [comment]
@roshin8 may be this example will help you? https://codesandbox.io/s/react-google-maps-api-polygon-edge-onmouseup-bug-forked-dhx81?file=/src/index.js

**Comment by Pipas** [comment]
If anyone is looking for a solution, I had the same problem and it turns out that using svg images, or in my case I was creating a Symbol, causes performance problems when used in bulk.

You can read more in this blogpost: https://cloud.google.com/blog/products/maps-platform/google-maps-platform-best-practices-optimization-and-performance-tips

**Comment by almudena-vila-cognito** [comment]
I'm experiencing the same issue. I need to render 10000+ points in the map using a custom icon - svg images ideally - and it is very slow.
I'm using Clusters to try to improve the performance, but when I use svg's or png's it is very slow, or making the page unresponsive.

Example using Google default icons: https://codesandbox.io/s/10000points-googleicon-vm7f5
Example with a custom svg: https://codesandbox.io/s/1000points-customsvg-3ysn1
Example using a png: https://codesandbox.io/s/10000points-png-7ww8r

Has anyone found a solution for this problem or does anyone have any recommendations about how we can implement this? Is it possible to render a lots of markers using a custom icon?

Thanks!

**Comment by Aarbel** [comment]
@almudena-vila-cognito have you found a solution ?

**Comment by almudena-vila-cognito** [comment]
@Aarbel we are using [supercluster](https://github.com/mapbox/supercluster) library for the clustering and the performance has improved a lot.

Here's an example of supercluster and react-google-maps-api: https://codesandbox.io/s/inspiring-fast-wou8k?file=/src/Map.tsx:3179-3212

**Comment by Aarbel** [comment]
wonderfull, thanks a lot for your tips / codesandbox
