### ISSUE TITLE
Create Places services and do nearby search

### ISSUE THREAD

**Issue by oluwadareseyi** [JustFly1984/react-google-maps-api#941]
Hello.

How do I create a new PlacesService? I tried doing it but it didn't work. PS: I already enabled the places library.

Check out the code:

``` let service;
const onMapLoad = useCallback((map) => {
    const bounds = new window.google.maps.LatLngBounds();
    mapRef.current = map;
    const request = {
      bounds: bounds,
      type: ["restaurant"],
    };
    service = new window.google.maps.places.PlacesService(map);
    service.nearbySearch(request, (results, status) => {
      if (status === window.google.maps.places.PlacesServiceStatus.OK) {
      console.log(results);
      }
    });
  }, []);
```

The function isn't logging anything to the console. I'd really appreciate some help, thanks.

**Comment by retzion** [comment]
I'm also trying to figure this out. Anyone? 🙏

**Comment by cyrfer** [comment]
@retzion @oluwadareseyi 
Me too. I can get the Places API call to return useful data, but **my map goes blank after I make the call**.

I posted my code over here that shows how I call the Places API. I think you are doing basically the same as I am.
https://github.com/JustFly1984/react-google-maps-api/issues/1338#issuecomment-736660946

One big difference in our codes is the way we get the map ref. In the link to the code above, you can see I only READ the map ref, rather than ASSIGN it.

Don't take any code I post as "truth". I am suffering from a big problem with my implementation.

I obtain the map ref in a top-level component like this:

```javascript

const TopLevel = ({
  currentPosition,
}) => {
  const refGoogleMap = useRef()

  return (
      <GoogleMap
        ref={refGoogleMap}
        onIdle={onIdleMap}
        onLoadMap={onLoadMap}
        mapContainerClassName={classes.mapContainer}
        zoom={mapCenterOffice ? 15 : 10}
        center={currentPosition
            ? currentPosition
            : {lat: 34.0, lng: -120.0}
          }
      >
      </GoogleMap>
  )
}
```

**Comment by JustFly1984** [comment]
@cyrfer I offer `paid` development services, if you have no time to use documentation. `ref` on`< GoogleMap/> doesn't work as it was in other unmaintained library. Use `onLoad` callback instead.
